### ISSUE TITLE
Сверстать главную страницу

### ISSUE THREAD

**Issue by kpozdnikin** [kpozdnikin/gastroprocto2#2]
Сделать статическую схему html + sass для отображения главной страницы согласно дизайну
https://www.figma.com/file/a0wG8e4PZD6kmpS41uqyhx/Doctor?node-id=0%3A1
Первая страница (Первый вариант называется)

**Comment by kpozdnikin** [comment]
![Uploading image.png…]()

**Comment by tihero87** [comment]
Ready
