### ISSUE TITLE
Выделить отдельную страницу для конкретной статьи /blog/:articleId

### ISSUE THREAD

**Issue by kpozdnikin** [kpozdnikin/gastroprocto2#7]
На эту страницу перенести контент 
![Снимок экрана 2020-03-07 в 11 17 34](https://user-images.githubusercontent.com/13619407/76139836-4b544a00-6065-11ea-8ac7-92bf8464ff94.png)

**Comment by kpozdnikin** [comment]
@tihero87 не забудь плз проставить статусы у задач

**Comment by tihero87** [comment]
done
